---
- name: Create directory to put files into
  become: true
  ansible.builtin.file:
    path: '/etc/cloudflared/'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Setup Cloudflare GPG Key
  ansible.builtin.shell: sudo mkdir -p --mode=0755 /usr/share/keyrings && curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
  register: setup_gpg
- debug: msg="{{ setup_gpg.stdout_lines }}"

- name: Setup Cloudflare APT Repo
  ansible.builtin.shell: echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
  register: setup_apt
- debug: msg="{{ setup_apt.stdout_lines }}"

- name: Install Cloudflared
  ansible.builtin.shell: sudo apt-get update && sudo apt-get install cloudflared
  register: install_cloudflared
- debug: msg="{{ install_cloudflared.stdout_lines }}"

- name: Remove Tunnel
  ignore_errors: true
  ansible.builtin.shell: sudo cloudflared service uninstall
  register: remove_cloudflared
- debug: msg="{{ remove_cloudflared.stdout_lines }}"

- name: Update Cloudflare Tunnel Config
  become: true
  ansible.builtin.template:
    src: config.yml.j2
    dest: '/etc/cloudflared/config.yml'
    owner: 'root'
    group: 'root'
    mode: '0644'
    force: yes

- name: Update Cloudflare Tunnel Creds
  become: true
  ansible.builtin.template:
    src: creds.json.j2
    dest: '/etc/cloudflared/{{ CF_TUNNEL_ID }}.json'
    owner: 'root'
    group: 'root'
    mode: '0644'
    force: yes

- name: Configure Tunnel
  become: true
  ansible.builtin.shell: sudo cloudflared service install
  register: configure_cloudflared
- debug: msg="{{ configure_cloudflared.stdout_lines }}"
