---
- name: Create directory to put files into
  become: true
  ansible.builtin.file:
    path: '/etc/cloudflared/'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Setup Cloudflare GPG Key
  ansible.builtin.shell: sudo mkdir -p --mode=0755 /usr/share/keyrings && curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
  register: setup_gpg
- debug: msg="{{ setup_gpg.stdout_lines }}"

- name: Setup Cloudflare APT Repo
  ansible.builtin.shell: echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
  register: setup_apt
- debug: msg="{{ setup_apt.stdout_lines }}"

- name: Install jq
  ansible.builtin.shell: sudo apt install jq -y
  register: setup_jq
- debug: msg="{{ setup_jq.stdout_lines }}"

- name: Install Cloudflared
  ansible.builtin.shell: sudo apt-get update && sudo apt-get install cloudflared
  register: install_cloudflared
- debug: msg="{{ install_cloudflared.stdout_lines }}"

- name: Setup Docker Prereqs
  ansible.builtin.shell: sudo apt-get install ca-certificates curl gnupg
  register: setup_docker_prereqs
- debug: msg="{{ setup_docker_prereqs.stdout_lines }}"

- name: Setup Docker GPG
  become: true
  ansible.builtin.shell: sudo install -m 0755 -d /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg && sudo chmod a+r /etc/apt/keyrings/docker.gpg
  register: setup_docker_gpg
- debug: msg="{{ setup_docker_gpg.stdout_lines }}"

- name: Setup Docker APT Repo
  become: true
  ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  register: setup_docker_repo
- debug: msg="{{ setup_docker_repo.stdout_lines }}"

- name: Install Docker
  ignore_errors: true
  ansible.builtin.shell: sudo apt update && sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
  register: install_docker
- debug: msg="{{ install_docker.stdout_lines }}"

- name: Remove Tunnel
  ignore_errors: true
  ansible.builtin.shell: sudo cloudflared service uninstall
  register: remove_cloudflared
- debug: msg="{{ remove_cloudflared.stdout_lines }}"

- name: Configure Tunnel
  become: true
  ansible.builtin.shell:
    cmd: sudo cloudflared service install $(jq -rn --arg AID "{{ CF_ACCOUNT_ID }}" --arg TID "{{ CF_TUNNEL_ID }}" --arg TS "{{ CF_TUNNEL_SECRET }}" '{a:$AID,t:$TID,s:$TS} | @base64')
  register: configure_cloudflared
  timeout: 30
- debug: msg="{{ configure_cloudflared.stdout_lines }}"
