name: Deploy Prod
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-prod:
    name: Deploy
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pulumi/actions@v4.5.0
        with:
          command: preview
          stack-name: personal-site-iac
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          TF_VAR_compartment_ocid: ${{ inputs.TF_VAR_COMPARTMENT_OCID }}
